-- 1
SELECT NOME, ANO
FROM FILMES

-- 2
SELECT NOME, ANO, DURACAO
FROM FILMES
ORDER BY ANO ASC 

-- 3
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE NOME = 'De Volta para o Futuro'

-- 4
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE ANO = 1997

-- 5
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE ANO > 2000

-- 6
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE DURACAO > 100 AND DURACAO < 150
ORDER BY DURACAO ASC

-- 7
SELECT ANO, COUNT(1) AS QUANTIDADE
FROM FILMES
GROUP BY ANO
ORDER BY QUANTIDADE DESC

-- 8
SELECT PrimeiroNome, UltimoNome
FROM ATORES
WHERE Genero = 'M'

-- 9
SELECT PrimeiroNome, UltimoNome
FROM ATORES
WHERE Genero = 'F'
ORDER BY PrimeiroNome ASC

-- 10
SELECT F.Nome, G.Genero
FROM Filmes F
INNER JOIN FilmesGenero FG ON F.Id = FG.IdFilme
INNER JOIN Generos G ON FG.IdGenero = G.Id

-- 11
SELECT F.Nome, G.Genero
FROM Filmes F
INNER JOIN FilmesGenero FG ON F.Id = FG.IdFilme
INNER JOIN Generos G ON FG.IdGenero = G.Id
WHERE G.Genero = 'Mistério'

-- 12
SELECT F.Nome, A.PrimeiroNome, A.UltimoNome, EF.Papel
FROM Filmes F
INNER JOIN ElencoFilme EF ON F.Id = EF.IdFilme
INNER JOIN Atores A ON EF.IdAtor = A.Id